# Generated by Django 5.1.7 on 2026-05-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_jeans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeans',
            options={'verbose_name': 'Jeans', 'verbose_name_plural': 'Jeans'},
        ),
    ]
